import = [ "~/.config/alacritty/catppuccin-mocha.toml" ]
shell = "nu"

[env]
TERM = "xterm-256color"

[window]
#decorations = "None"
opacity = 0.9
blur = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
